[0m10:32:00.763642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742eda525be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742eda2aa4e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742edc6040e0>]}


============================== 10:32:00.769797 | 5406d8b0-59ea-433b-ba2f-ff62dcab239d ==============================
[0m10:32:00.769797 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:32:00.770630 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/codespace/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init tesouro', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:32:00.784656 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/home/codespace/.dbt')}
[0m10:32:00.785278 [info ] [MainThread]: Creating dbt configuration folder at 
[0m10:32:00.786795 [debug] [MainThread]: Starter project path: /usr/local/python/3.12.1/lib/python3.12/site-packages/dbt/include/starter_project
[0m10:32:00.793488 [info ] [MainThread]: 
Your new dbt project "tesouro" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:32:00.794158 [info ] [MainThread]: Setting up your profile.
[0m10:32:08.034569 [info ] [MainThread]: Profile tesouro written to /home/codespace/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m10:32:08.037470 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 7.3254538, "process_in_blocks": "78472", "process_kernel_time": 0.191361, "process_mem_max_rss": "114512", "process_out_blocks": "72", "process_user_time": 1.491233}
[0m10:32:08.038302 [debug] [MainThread]: Command `dbt init` succeeded at 10:32:08.038168 after 7.33 seconds
[0m10:32:08.038831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742ed9f93350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742eddf23aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x742ed9d0e570>]}
[0m10:32:08.039372 [debug] [MainThread]: Flushing usage events
[0m10:32:08.374821 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:36:49.187404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a41107a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a40e37d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a40e2ba0>]}


============================== 10:36:49.190771 | ec9d0afc-2590-4637-a7ba-a98fc1bc3049 ==============================
[0m10:36:49.190771 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:36:49.191596 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/codespace/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:36:49.192236 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/analytics_engineering_curse/curso/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:36:49.193311 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05818168, "process_in_blocks": "0", "process_kernel_time": 0.115527, "process_mem_max_rss": "92660", "process_out_blocks": "24", "process_user_time": 1.318607}
[0m10:36:49.193875 [debug] [MainThread]: Command `dbt run` failed at 10:36:49.193760 after 0.06 seconds
[0m10:36:49.194330 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a618f590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a41107a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c12a3c57200>]}
[0m10:36:49.194857 [debug] [MainThread]: Flushing usage events
[0m10:36:49.537130 [debug] [MainThread]: An error was encountered while trying to flush usage events
